### ISSUE TITLE
I'm getting an error on the continous example

### ISSUE THREAD

**Issue by quiktea** [St3veR0nin/cleverbot_free#1]
```Traceback (most recent call last):
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\idk.py", line 15, in <module>
    main()
  File ".\idk.py", line 6, in main
    cb.init()
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\site-packages\cleverbot_free\cbapi.py", line 48, in init
    self.wd = webdriver.Chrome(options=self.options)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home```

is there a way to fix this

**Comment by WilliamRichards1740** [comment]
Im having the same issue

**Comment by St3veR0nin** [comment]
Hi, first of all, thanks a lot for the interest in this library :)

The fix for this error is actually pretty simple...
 
As stated in the last line of the traceback you got, this error is generated due to a `selenium.common.exceptions.WebDriverException`, specifically, the error message says this:
`'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

This library relies on `selenium` and a specific webdriver, which is the `chromedriver`. The chromedriver ( which is basically an .exe file downloadable from this site `https://chromedriver.chromium.org/` ), needs to be in the PATH environment variable, so that every software trying to use it, can easily access it from every location in your computer.

To fix this error, please add the full path to your chromedriver.exe into the PATH environment variable ( for one user or even for the entire system ), if you don't know how to set up PATH environment variable, you can refer to these StackOverflow answers:

-Under Windows: [https://stackoverflow.com/a/44272417](https://stackoverflow.com/a/44272417)

-Under Linux: [https://stackoverflow.com/a/14638025](https://stackoverflow.com/a/14638025)

Alternatively, you could also hardcode the chromedriver path into the library by replacing this line in the **_init()_** method:

from this 
`self.wd = webdriver.Chrome(options=self.options)`
to this
`self.wd = webdriver.Chrome(CHROMEDRIVER_PATH_STRING, options=self.options)`

**Comment by quiktea** [comment]
Thanks @St3veR0nin
